### ISSUE TITLE
Unable to Install

### ISSUE THREAD

**Issue by kimlabSchatterjee** [ambrishroy/LIGSIFT#5]
I am using Linuxmint 19.2

I set the pat as per instruction . I received following error.
(base) kimlab@kimlab:/media/kimlab/D_Drive/Software/LIGSIFT-master$ make -j5
g++ -c -O3 -Wall -I/usr/local/include/openbabel3/openbabel main.cpp 
g++ -c -O3 -Wall -I/usr/local/include/openbabel3/openbabel Smallmolecule.cpp -o sm.o
In file included from /usr/include/c++/7/clocale:42:0,
                 from /usr/include/x86_64-linux-gnu/c++/7/bits/c++locale.h:41,
                 from /usr/include/c++/7/bits/localefwd.h:40,
                 from /usr/include/c++/7/string:43,
                 from Smallmolecule.h:4,
                 from Smallmolecule.cpp:1:
/usr/local/include/openbabel3/openbabel/locale.h:23:10: fatal error: openbabel/babelconfig.h: No such file or directory
 #include <openbabel/babelconfig.h>
          ^~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
Makefile:38: recipe for target 'sm.o' failed
make: *** [sm.o] Error 1
make: *** Waiting for unfinished jobs....
In file included from /usr/include/c++/7/clocale:42:0,
                 from /usr/include/x86_64-linux-gnu/c++/7/bits/c++locale.h:41,
                 from /usr/include/c++/7/bits/localefwd.h:40,
                 from /usr/include/c++/7/ios:41,
                 from /usr/include/c++/7/ostream:38,
                 from /usr/include/c++/7/iostream:39,
                 from main.cpp:11:
/usr/local/include/openbabel3/openbabel/locale.h:23:10: fatal error: openbabel/babelconfig.h: No such file or directory
 #include <openbabel/babelconfig.h>
          ^~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
Makefile:35: recipe for target 'main.o' failed
make: *** [main.o] Error 1

Kindly help

**Comment by LionThu1** [comment]
Hi, While trying to install, I ran into the same error. Have you been able to find a solution to the problem? 

Would it work with Obabel 2.4, the internal file structure of obabel seems to have changed somewhat between version? 

(Using Ubuntu)

**Comment by LionThu1** [comment]
Update. 
Made it work. 

It works with Obabel 2.4.1; you can get the old versions from Git Hub and then build from the source. 
It helped me install it as described in the README, especially setting a -DCMAKE Libary like in step 3. (e) . (note ../openbabel does not exist when executed from obbuild/, you have to  modify it like this: (cmake ..  -DCMAKE_INSTALL_PREFIX=/home/$USRNAME/bin/) )

Then, in ~/bin/, you will find a bin/, lib/ and include/ folder, which the Makefile asks for. 
in the makefile it would then look like this: INCLUDE =-I/home/$USRNAME/bin/include/openbabel-2.0, and simular for the other paths. 

But then it will compile and run. 
 Tested with the newest Ubuntu and GCC-11 .
